<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE personas [
  <!ELEMENT personas (persona+)>
  <!ELEMENT persona (nombre, apellidos, (hombre | mujer), nacimiento?, direccion+)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellidos (#PCDATA)>
  <!ELEMENT hombre EMPTY>
  <!ELEMENT mujer EMPTY>
  <!ELEMENT nacimiento (#PCDATA)>
  <!ELEMENT direccion (calle, poblacion, provincia, codigopostal?)>
  <!ELEMENT calle (#PCDATA)>
  <!ELEMENT poblacion (#PCDATA)>
  <!ELEMENT provincia (#PCDATA)>
  <!ELEMENT codigopostal (#PCDATA)>

  <!ATTLIST nacimiento dia CDATA #REQUIRED>
  <!ATTLIST nacimiento mes CDATA #REQUIRED>
  <!ATTLIST nacimiento anyo CDATA #REQUIRED>
]>

<personas>

  <persona>
    <nombre></nombre>
    <apellidos></apellidos>
    <mujer />
    <nacimiento dia="1" mes="10" anyo="2000"></nacimiento>
    <direccion>
      <calle></calle>
      <poblacion></poblacion>
      <provincia></provincia>
      <codigopostal></codigopostal>
    </direccion>
  </persona>

</personas>