<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE entrenamiento [
  <!ELEMENT entrenamiento (cliente+, sesion+)>
  <!ELEMENT cliente (nombre, apellido1, apellido2?, id)>
  <!ELEMENT sesion (duracion, distancia, localizacion, comentario?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido1 (#PCDATA)>
  <!ELEMENT apellido2 (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT duracion (#PCDATA)>
  <!ELEMENT distancia (#PCDATA)>
  <!ELEMENT localizacion (#PCDATA)>
  <!ELEMENT comentario (#PCDATA)>

  <!ATTLIST sesion actividad (running | natacion | bicicleta) "running">
  <!ATTLIST sesion pulsaciones CDATA #IMPLIED>
  <!ATTLIST sesion id-cliente CDATA #REQUIRED>
  <!ATTLIST duracion unidad (minutos | segundos | horas) "minutos">
  <!ATTLIST distancia unidad (kilometros | millas | vuelta) "kilometros">

]>
<entrenamiento>
  <cliente>
    <nombre></nombre>
    <apellido1></apellido1>
    <apellido2></apellido2>
    <id></id>
  </cliente>

  <sesion actividad="running" pulsaciones="2" id-cliente="1">
    <duracion unidad="minutos"></duracion>
    <distancia unidad="kilometros"></distancia>
    <localizacion></localizacion>
    <comentario></comentario>
  </sesion>
  
</entrenamiento>